[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
registry = "3RVBZDA6dgcjkGJtXRJxLvLh5g8qY6QwGHoribyKPN2E"
dex-adapter = "HwGMSaJuVN5xAJLXFy9pkP4znPgm19PGSAtJZyf1CFu2"

[programs.devnet]
registry = "3RVBZDA6dgcjkGJtXRJxLvLh5g8qY6QwGHoribyKPN2E"
dex-adapter = "HwGMSaJuVN5xAJLXFy9pkP4znPgm19PGSAtJZyf1CFu2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
test = "bun test"
