[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
registry = "3RVBZDA6dgcjkGJtXRJxLvLh5g8qY6QwGHoribyKPN2E"
dex-adapter = "FMsjKKPk7FQb1B9H8UQTLrdCUZ9MaoAeTnNK9kdVJmtt"

[programs.devnet]
registry = "3RVBZDA6dgcjkGJtXRJxLvLh5g8qY6QwGHoribyKPN2E"
dex-adapter = "FMsjKKPk7FQb1B9H8UQTLrdCUZ9MaoAeTnNK9kdVJmtt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
test = "bun test"
