[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
registry = "3XEw4Ta4PU5NMET3xJhc71yagoB85awhTzzcNdFbAyBt"
dex-adapter = "3XEw4Ta4PU5NMET3xJhc71yagoB85awhTzzcNdFbAyBt"

[programs.devnet]
registry = "3XEw4Ta4PU5NMET3xJhc71yagoB85awhTzzcNdFbAyBt"
dex-adapter = "3XEw4Ta4PU5NMET3xJhc71yagoB85awhTzzcNdFbAyBt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
test = "bun test"
