[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft = "7sHJDPbAHy5uj7Guz5XD2AgRFKp3KMvYYvNwwTvyw9Lg"
staking = "FS3fX9yzYMkurJPXsPeFY1mt8pCQtbTQSDQqpR61wkhb"

[programs.devnet]
nft = "7sHJDPbAHy5uj7Guz5XD2AgRFKp3KMvYYvNwwTvyw9Lg"
staking = "FS3fX9yzYMkurJPXsPeFY1mt8pCQtbTQSDQqpR61wkhb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
test = "bun test"
# test = "bun test --test-name-pattern staking"
