[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft = "7sHJDPbAHy5uj7Guz5XD2AgRFKp3KMvYYvNwwTvyw9Lg"
staking = "FS3fX9yzYMkurJPXsPeFY1mt8pCQtbTQSDQqpR61wkhb"
marketplace = "DWTez7iNT13kaqEEZfzFQb5Msv7JdF9EFKRize99wQTi"

[programs.devnet]
nft = "7sHJDPbAHy5uj7Guz5XD2AgRFKp3KMvYYvNwwTvyw9Lg"
staking = "FS3fX9yzYMkurJPXsPeFY1mt8pCQtbTQSDQqpR61wkhb"
marketplace = "DWTez7iNT13kaqEEZfzFQb5Msv7JdF9EFKRize99wQTi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
# test = "bun test"
test = "bun test marketplace"
