[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "8Y1PPAsKbeKiT361EbKeCrU9yE1bNLXWNnM7va2PMQ67"

[programs.devnet]
staking = "8Y1PPAsKbeKiT361EbKeCrU9yE1bNLXWNnM7va2PMQ67"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/dev/.test-wallets/solana/dev-keypair.json"

[scripts]
test = "bun test"
# test = "bun test --test-name-pattern staking"
